version: "3.7"

services:
  hargassner_sucker:
    build: "."
    network_mode: "host"
    env_file:
      # HEIZKESSEL_HOST
      # MQTT_HOST
      # MQTT_API_KEY
      - ".env"
    volumes:
      - ".:/usr/src/app"
